//! Worktree scanning: walk, exclude, analyze, and *report* what was skipped.
//!
//! Silent omission is worse than an error: if minified JavaScript and generated
//! protobuf stubs are quietly dropped, the first run's top-K looks plausible
//! and the summary lies by omission. Every file left out for a reason lands in
//! a [`SkipStats`] bucket.

use std::io;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use globset::{Glob, GlobSet, GlobSetBuilder};
use ignore::WalkBuilder;
use rayon::prelude::*;
use serde::Serialize;

use crate::{FunctionMetrics, Language, analyze_source};

/// Default per-file size ceiling: minified or vendored blobs are not reviewable
/// code and would otherwise own the whole top-K.
pub const DEFAULT_MAX_FILE_BYTES: u64 = 1024 * 1024;

/// Directories that are never walked.
const EXCLUDED_DIRS: &[&str] = &[
    "target",
    "node_modules",
    "vendor",
    "third_party",
    // `third-party` and `open_source` are the same class: vendored trees
    // under those exact names on this machine (MG-Nav, Hi3863_SmartCar).
    "third-party",
    "open_source",
    "dist",
    "build",
    ".venv",
    "venv",
    "site-packages",
    "__pycache__",
    ".direnv",
    ".devenv",
    ".git",
    ".jj",
    ".next",
    ".turbo",
];

/// File-name patterns for machine output rather than reviewed code.
const GENERATED_PATTERNS: &[&str] = &[
    "*.min.js",
    "*.min.mjs",
    "*.min.cjs",
    "*.min.css",
    "*.map",
    "*.pb.go",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.g.dart",
    "*.freezed.dart",
    "*.designer.cs",
    "*_generated.go",
    "*.generated.*",
];

/// Directory names that mark machine output.
const GENERATED_DIRS: &[&str] = &["generated", "autogenerated"];

/// Code extensions with no bundled grammar: counted as `unsupported` so the
/// gap in coverage is visible instead of looking like clean code.
const UNSUPPORTED_CODE_EXTENSIONS: &[&str] = &[
    "c", "h", "cc", "cpp", "cxx", "hpp", "hh", "cs", "rb", "php", "swift", "kt", "kts", "scala",
    "sh", "bash", "zsh", "fish", "lua", "pl", "pm", "r", "jl", "dart", "zig", "hs", "ml", "mli",
    "clj", "cljs", "ex", "exs", "erl", "elm", "vue", "svelte", "astro", "sql", "proto", "groovy",
];

/// A scanned file and the functions found in it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileComplexity {
    pub path: PathBuf,
    pub language: Language,
    pub functions: Vec<FunctionMetrics>,
    /// File-level nloc: non-blank, non-comment lines of the whole file,
    /// same rules as the per-function nloc. A module-organization signal,
    /// ranked on its own table — never a threshold on functions.
    pub nloc: u32,
}

impl FileComplexity {
    /// Worst cognitive complexity among the file's functions (0 when empty).
    pub fn worst_cognitive(&self) -> u32 {
        self.functions
            .iter()
            .map(|function| function.metrics.cognitive)
            .max()
            .unwrap_or(0)
    }

    /// Worst cyclomatic complexity among the file's functions (0 when empty).
    pub fn worst_cc(&self) -> u32 {
        self.functions
            .iter()
            .map(|function| function.metrics.cc)
            .max()
            .unwrap_or(0)
    }
}

/// Files left out of the scan, by reason.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SkipStats {
    pub generated: u32,
    pub unsupported: u32,
    pub too_large: u32,
}

impl SkipStats {
    pub fn total(self) -> u32 {
        self.generated + self.unsupported + self.too_large
    }
}

/// What to scan and what to leave alone.
#[derive(Debug, Clone)]
pub struct ScanOptions {
    /// Root the reported paths are relative to (and the default scan target).
    pub root: PathBuf,
    /// Paths to walk; defaults to `[root]`.
    pub paths: Vec<PathBuf>,
    /// Include globs. Empty means everything.
    pub include: Vec<String>,
    /// Exclude globs, on top of the built-in list.
    pub exclude: Vec<String>,
    /// Files larger than this are skipped as `tooLarge`.
    pub max_file_bytes: u64,
}

impl ScanOptions {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        let root = root.into();
        Self {
            paths: vec![root.clone()],
            root,
            include: Vec::new(),
            exclude: Vec::new(),
            max_file_bytes: DEFAULT_MAX_FILE_BYTES,
        }
    }
}

/// Result of one scan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScanReport {
    /// Absolute root the `files` paths are relative to.
    pub root: PathBuf,
    pub files: Vec<FileComplexity>,
    pub skipped: SkipStats,
}

impl ScanReport {
    /// Total number of functions across all analyzed files.
    pub fn function_count(&self) -> usize {
        self.files.iter().map(|file| file.functions.len()).sum()
    }
}

/// Walk, parse and analyze everything the options select.
pub fn scan(options: &ScanOptions) -> io::Result<ScanReport> {
    let root = std::fs::canonicalize(&options.root).unwrap_or_else(|_| options.root.clone());
    let include = build_globset(&options.include)?;
    let exclude = build_globset(&options.exclude)?;

    let mut candidates = Vec::new();
    for path in &options.paths {
        if !path.exists() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("no such path: {}", path.display()),
            ));
        }
        collect_files(path, &mut candidates);
    }
    candidates.sort();
    candidates.dedup();

    let outcomes: Vec<Outcome> = candidates
        .par_iter()
        .map(|path| analyze_candidate(path, options, &include, &exclude))
        .collect();

    let mut files = Vec::new();
    let mut skipped = SkipStats::default();
    for outcome in outcomes {
        match outcome {
            Outcome::Analyzed(file) => files.push(file),
            Outcome::Skipped(SkipKind::Generated) => skipped.generated += 1,
            Outcome::Skipped(SkipKind::Unsupported) => skipped.unsupported += 1,
            Outcome::Skipped(SkipKind::TooLarge) => skipped.too_large += 1,
            Outcome::Ignored => {}
        }
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));

    Ok(ScanReport {
        root,
        files,
        skipped,
    })
}

/// Render `path` for display: relative to `root` when it is inside it.
pub fn relative_path(root: &Path, path: &Path) -> String {
    let path = path.strip_prefix(root).unwrap_or(path);
    path.to_string_lossy().replace('\\', "/")
}

enum Outcome {
    Analyzed(FileComplexity),
    Skipped(SkipKind),
    Ignored,
}

enum SkipKind {
    Generated,
    Unsupported,
    TooLarge,
}

/// Walk one path the way [`scan`] does (excludes, ignore files), collecting
/// every file. Shared by the complexity scan and the dependency graph walk.
pub(crate) fn collect_files(path: &Path, out: &mut Vec<PathBuf>) {
    if path.is_file() {
        out.push(path.to_path_buf());
        return;
    }
    let mut builder = WalkBuilder::new(path);
    builder
        // `require_git(false)`: a jj repository has no top-level `.git`
        // directory unless it is colocated, and `.gitignore` must still apply.
        .require_git(false)
        .hidden(true)
        .ignore(true)
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        .parents(true)
        .filter_entry(|entry| {
            !(entry.file_type().is_some_and(|kind| kind.is_dir())
                && EXCLUDED_DIRS.contains(&entry.file_name().to_string_lossy().as_ref()))
        });
    for entry in builder.build().flatten() {
        if entry.file_type().is_some_and(|kind| kind.is_file()) {
            out.push(entry.into_path());
        }
    }
}

fn analyze_candidate(
    path: &Path,
    options: &ScanOptions,
    include: &GlobSet,
    exclude: &GlobSet,
) -> Outcome {
    if !options.include.is_empty() && !include.is_match(path) {
        return Outcome::Ignored;
    }
    if exclude.is_match(path) {
        return Outcome::Ignored;
    }
    if is_generated(path) {
        return Outcome::Skipped(SkipKind::Generated);
    }

    let Some(language) = Language::from_path(path) else {
        return if has_unsupported_code_extension(path) {
            Outcome::Skipped(SkipKind::Unsupported)
        } else {
            Outcome::Ignored
        };
    };

    match std::fs::metadata(path) {
        Ok(metadata) if metadata.len() > options.max_file_bytes => {
            return Outcome::Skipped(SkipKind::TooLarge);
        }
        Ok(_) => {}
        Err(_) => return Outcome::Ignored,
    }

    let Ok(source) = std::fs::read(path) else {
        return Outcome::Ignored;
    };
    let analysis = analyze_source(language, &source);
    Outcome::Analyzed(FileComplexity {
        path: path.to_path_buf(),
        language,
        functions: analysis.functions,
        nloc: analysis.nloc,
    })
}

/// Whether a path matches the built-in machine-output heuristics.
pub(crate) fn is_generated(path: &Path) -> bool {
    generated_globs().is_match(path) || has_generated_component(path)
}

fn has_generated_component(path: &Path) -> bool {
    path.components()
        .any(|component| GENERATED_DIRS.contains(&component.as_os_str().to_string_lossy().as_ref()))
}

fn has_unsupported_code_extension(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            UNSUPPORTED_CODE_EXTENSIONS.contains(&extension.to_ascii_lowercase().as_str())
        })
}

fn generated_globs() -> &'static GlobSet {
    static GLOBS: OnceLock<GlobSet> = OnceLock::new();
    GLOBS.get_or_init(|| {
        build_globset_str(GENERATED_PATTERNS).expect("built-in generated-file globs are valid")
    })
}

fn build_globset(patterns: &[String]) -> io::Result<GlobSet> {
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        let glob = Glob::new(pattern).map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("invalid glob {pattern:?}: {error}"),
            )
        })?;
        builder.add(glob);
    }
    builder
        .build()
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidInput, error.to_string()))
}

fn build_globset_str(patterns: &[&str]) -> io::Result<GlobSet> {
    let owned: Vec<String> = patterns
        .iter()
        .map(|pattern| (*pattern).to_string())
        .collect();
    build_globset(&owned)
}
