/**
 * Mock 审批数据 —— 接入 daemon review 会话数据源前的占位。
 * 后续接线见 .scratch/home-approvals-ui/。
 */
import type { ReviewSubmission } from './types'

export const mockSubmissions: ReviewSubmission[] = [
  {
    id: 'r-2412',
    type: 'confirm',
    title: '请求运行 cargo test --workspace（预计 4 分钟）',
    source: 'pi @ ws/sandbox',
    repo: 'qingluan',
    severity: 'low',
    status: 'pending',
    age: '8 分钟前',
    ageHours: 0.15,
    comments: 0,
    excerpt: ['沙箱内执行，网络隔离，CPU 预算 5 分钟'],
  },
  {
    id: 'r-2413',
    type: 'confirm',
    title: '打算把 storage 层改为 tokio 异步，是否同意？',
    source: 'pi @ ws/storage',
    repo: 'qingluan',
    severity: 'medium',
    status: 'pending',
    age: '40 分钟前',
    ageHours: 0.7,
    comments: 0,
    excerpt: ['涉及 6 个文件约 800 行；现有同步实现已有测试覆盖'],
  },
  {
    id: 'r-2414',
    type: 'confirm',
    title: '请求安装 dev-dependency: criterion 0.5（基准测试用）',
    source: 'pi @ ws/bench',
    repo: 'qingluan',
    severity: 'low',
    status: 'pending',
    age: '2 小时前',
    ageHours: 2,
    comments: 0,
    excerpt: ['仅 dev-dependency，不影响发布产物'],
  },
  {
    id: 'r-2415',
    type: 'confirm',
    title: 'Mini-Nav 数据集下载 12 GB，请求放行带宽',
    source: 'pi @ mini-nav',
    repo: 'mini-nav',
    severity: 'medium',
    status: 'pending',
    age: '5 小时前',
    ageHours: 5,
    comments: 0,
    excerpt: ['下载到 workspace 本地缓存，不进 git'],
  },
  {
    id: 'r-2401',
    type: 'diff',
    title: 'feat(sandbox): cgroup v2 委托检测前移到 daemon 启动',
    source: 'pi @ ws/sandbox',
    repo: 'qingluan',
    branch: 'feat/cgroup-delegate',
    severity: 'high',
    status: 'pending',
    age: '23 分钟前',
    ageHours: 0.4,
    comments: 0,
    files: 9,
    additions: 412,
    deletions: 87,
    commits: 14,
    range: 'main..feat/cgroup-delegate',
    commitList: [
      { hash: 'a3f9c21', subject: 'sandbox: 抽出 delegate 探测模块' },
      { hash: '7b2e084', subject: 'daemon: 启动时预检 cgroup v2 委托' },
      { hash: 'e11d55f', subject: 'tests: 委托失败的三种降级路径' },
    ],
    fileList: [
      { path: 'crates/qingluan-sandbox/src/delegate.rs', additions: 186, deletions: 22 },
      { path: 'crates/qingluan-daemon/src/boot.rs', additions: 94, deletions: 31 },
      { path: 'crates/qingluan-sandbox/src/lib.rs', additions: 77, deletions: 12 },
      { path: 'tests/delegate_check.rs', additions: 41, deletions: 18 },
      { path: 'docs/sandbox.md', additions: 14, deletions: 4 },
    ],
  },
  {
    id: 'r-2402',
    type: 'markdown',
    title: 'ADR-008：terminal gRPC 只走 UDS 的取舍记录',
    source: 'pi @ notes',
    repo: 'notes',
    severity: 'medium',
    status: 'pending',
    age: '1 小时前',
    ageHours: 1,
    comments: 0,
    blocks: 14,
    excerpt: [
      '# ADR-008 terminal gRPC 只走 UDS',
      '## 背景',
      'terminal 数据流曾评估 TCP + UDS 双通道；TCP 暴露面大，且局域网场景无真实需求。',
      '## 决定',
      'gRPC 终端通道固定使用私有 UDS，daemon 不提供 TCP 终端端口。',
    ],
  },
  {
    id: 'r-2403',
    type: 'diff',
    title: 'fix(daemon): review 会话创建与 diff 快照的竞态',
    source: 'pi @ ws/review-fix',
    repo: 'qingluan',
    branch: 'fix/review-race',
    severity: 'high',
    status: 'pending',
    age: '2 小时前',
    ageHours: 2,
    comments: 2,
    files: 4,
    additions: 96,
    deletions: 23,
    commits: 3,
    range: 'main..fix/review-race',
    commitList: [
      { hash: 'c94a1b7', subject: 'daemon: review 会话加写锁' },
      { hash: '0d3f8ea', subject: 'storage: 快照先落盘再登记' },
      { hash: '5a6b2c9', subject: 'tests: 并发创建 100 会话回归' },
    ],
    fileList: [
      { path: 'crates/qingluan-daemon/src/review.rs', additions: 68, deletions: 9 },
      { path: 'crates/qingluan-storage/src/snapshot.rs', additions: 21, deletions: 11 },
      { path: 'tests/review_race.rs', additions: 7, deletions: 3 },
    ],
  },
  {
    id: 'r-2404',
    type: 'diff',
    title: 'baseuilib: 新增 DataTable 组件（含虚拟滚动）',
    source: 'pi @ ws/data-table',
    repo: 'baseuilib',
    branch: 'feat/data-table',
    severity: 'medium',
    status: 'pending',
    age: '3 小时前',
    ageHours: 3,
    comments: 0,
    files: 17,
    additions: 1204,
    deletions: 31,
    commits: 22,
    range: 'develop..feat/data-table',
    commitList: [
      { hash: 'f01a9c3', subject: 'widget: DataTable 骨架与行模型' },
      { hash: '9c7e2d0', subject: 'widget: 虚拟滚动视口裁剪' },
      { hash: '3d8b4f1', subject: 'assets: zh_cn 语言键补齐' },
    ],
    fileList: [
      { path: 'src/main/java/.../widget/DataTable.java', additions: 731, deletions: 0 },
      { path: 'src/main/java/.../widget/table/TableModel.java', additions: 284, deletions: 6 },
      { path: 'src/main/resources/assets/baseui/lang/zh_cn.json', additions: 89, deletions: 12 },
      { path: 'src/test/java/.../DataTableTest.java', additions: 100, deletions: 13 },
    ],
  },
  {
    id: 'r-2405',
    type: 'markdown',
    title: 'BaseUI 文档：BlockFrame 交互壳层章节草稿',
    source: 'pi @ baseui-docs',
    repo: 'baseui-docs',
    severity: 'low',
    status: 'pending',
    age: '今早 09:12',
    ageHours: 6,
    comments: 0,
    blocks: 9,
    excerpt: [
      '# BlockFrame 交互壳层',
      'BlockFrame 是所有 block 的交互容器：选中态、悬停工具条与评论锚点都由它提供。',
      '> 示例代码与 API 表格待补。',
    ],
  },
  {
    id: 'r-2406',
    type: 'markdown',
    title: 'Mini-Nav 实验周报：场景图预训练数据清洗',
    source: 'pi @ mini-nav',
    repo: 'mini-nav',
    severity: 'high',
    status: 'pending',
    age: '昨天 18:40',
    ageHours: 20,
    comments: 1,
    blocks: 22,
    excerpt: [
      '# 场景图预训练数据清洗 · 周报',
      '本周清理了 3 组离线场景图数据，剔除 12% 姿态漂移样本。',
      '## 结论：清洗后 val SPL 提升 2.4，但嵌入式端推理耗时增加 8ms，待评估。',
    ],
  },
  {
    id: 'r-2407',
    type: 'diff',
    title: 'refactor(hfccore): 注册表延迟初始化',
    source: 'pi @ ws/hfccore',
    repo: 'hfccore',
    branch: 'refactor/registry',
    severity: 'medium',
    status: 'in-review',
    age: '昨天 15:02',
    ageHours: 24,
    comments: 6,
    files: 11,
    additions: 318,
    deletions: 402,
    commits: 8,
    range: 'main..refactor/registry',
    commitList: [
      { hash: 'b72c9e4', subject: 'core: Registry 拆出 LazyHolder' },
      { hash: '1e5a7f3', subject: 'event: EventBus 改弱引用' },
    ],
    fileList: [
      { path: 'src/main/java/.../core/Registry.java', additions: 156, deletions: 288 },
      { path: 'src/main/java/.../core/LazyHolder.java', additions: 102, deletions: 14 },
      { path: 'src/main/java/.../event/EventBus.java', additions: 60, deletions: 100 },
    ],
  },
  {
    id: 'r-2408',
    type: 'markdown',
    title: 'pi-extensions：subagent 委派规范 v2',
    source: 'pi @ pi-extensions',
    repo: 'pi-extensions',
    severity: 'low',
    status: 'in-review',
    age: '昨天 11:20',
    ageHours: 27,
    comments: 3,
    blocks: 18,
    excerpt: [
      '# subagent 委派规范 v2',
      'v1 的边界讨论过长；v2 收敛为「先描述、再授权、后回收」三段式。',
      '## 开放问题：委派失败的回滚语义尚未定稿。',
    ],
  },
  {
    id: 'r-2409',
    type: 'diff',
    title: 'chore(baseui-docs): rspress 主题色统一',
    source: 'pi @ baseui-docs',
    repo: 'baseui-docs',
    branch: 'chore/theme',
    severity: 'low',
    status: 'in-review',
    age: '前天 20:11',
    ageHours: 44,
    comments: 1,
    files: 6,
    additions: 54,
    deletions: 60,
    commits: 2,
    range: 'main..chore/theme',
    commitList: [
      { hash: '6f8d1a2', subject: 'theme: 主题变量收敛到 vars.css' },
      { hash: 'a09c3f7', subject: 'theme: 品牌色对齐 BaseUI' },
    ],
    fileList: [
      { path: 'theme/index.ts', additions: 30, deletions: 34 },
      { path: 'theme/vars.css', additions: 24, deletions: 26 },
    ],
  },
  {
    id: 'r-2410',
    type: 'diff',
    title: 'feat(cli): qingluan review export --format json',
    source: 'pi @ ws/review-export',
    repo: 'qingluan',
    branch: 'feat/export-json',
    severity: 'high',
    status: 'awaiting',
    age: '昨天 10:05',
    ageHours: 29,
    comments: 4,
    files: 5,
    additions: 187,
    deletions: 12,
    commits: 6,
    range: 'main..feat/export-json',
    commitList: [
      { hash: 'd45b8c1', subject: 'protocol: ReviewExport 消息定义' },
      { hash: '8f2a6e3', subject: 'cli: review export 子命令' },
      { hash: '2c9d7f0', subject: 'docs: cli.md 补导出示例' },
    ],
    fileList: [
      { path: 'crates/qingluan-cli/src/commands/review.rs', additions: 112, deletions: 4 },
      { path: 'crates/qingluan-protocol/src/review.rs', additions: 55, deletions: 6 },
      { path: 'docs/cli.md', additions: 20, deletions: 2 },
    ],
  },
  {
    id: 'r-2411',
    type: 'diff',
    title: 'feat(web): markdown block 评论气泡',
    source: 'pi @ ws/web',
    repo: 'qingluan',
    branch: 'feat/block-comment',
    severity: 'medium',
    status: 'awaiting',
    age: '前天 16:30',
    ageHours: 52,
    comments: 2,
    files: 8,
    additions: 466,
    deletions: 24,
    commits: 11,
    range: 'main..feat/block-comment',
    commitList: [
      { hash: 'e7f3a5b', subject: 'web: BlockFrame 评论锚点' },
      { hash: '4b1c9d8', subject: 'web: useBlockComments 组合式' },
      { hash: '0a8e2f6', subject: 'store: reviewComments 会话隔离' },
    ],
    fileList: [
      { path: 'apps/web/src/components/markdown/BlockFrame.vue', additions: 121, deletions: 8 },
      { path: 'apps/web/src/composables/useBlockComments.ts', additions: 98, deletions: 2 },
      { path: 'apps/web/src/stores/reviewComments.ts', additions: 143, deletions: 6 },
    ],
  },
  {
    id: 'r-2398',
    type: 'diff',
    title: 'fix(web): diff 行内评论定位偏移',
    source: 'pi @ ws/web',
    repo: 'qingluan',
    severity: 'medium',
    status: 'done',
    age: '昨天 09:14',
    ageHours: 31,
    comments: 5,
    files: 2,
    additions: 46,
    deletions: 18,
    commits: 1,
    range: 'main..fix/inline-anchor',
    fileList: [
      {
        path: 'apps/web/src/components/code-review/CodeReviewDiff.vue',
        additions: 31,
        deletions: 12,
      },
      { path: 'apps/web/src/lib/review-api.ts', additions: 15, deletions: 6 },
    ],
  },
  {
    id: 'r-2397',
    type: 'markdown',
    title: 'README 快速上手重写',
    source: 'pi @ notes',
    repo: 'qingluan',
    severity: 'low',
    status: 'done',
    age: '昨天 08:02',
    ageHours: 32,
    comments: 2,
    blocks: 12,
  },
  {
    id: 'r-2396',
    type: 'diff',
    title: 'feat(cli): health 子命令',
    source: 'pi @ ws/cli',
    repo: 'qingluan',
    severity: 'low',
    status: 'done',
    age: '前天 11:47',
    ageHours: 48,
    comments: 0,
    files: 3,
    additions: 78,
    deletions: 5,
    commits: 4,
    range: 'main..feat/health-cmd',
  },
]

/**
 * Markdown 提交的完整 block 文档（详情页 /markdown-review/:id 用）。
 * key 与 ReviewSubmission.id 对应；接 daemon 后由审查会话提供。
 */
import type { MarkdownBlock } from '@/markdown/types'

export const markdownDocs: Record<string, MarkdownBlock[]> = {
  'r-2402': [
    { id: 'b-1', type: 'heading', order: 1, depth: 1, text: 'ADR-008：terminal gRPC 只走 UDS' },
    { id: 'b-2', type: 'paragraph', order: 2, text: '状态：已接受（2026-04-24）' },
    {
      id: 'b-3',
      type: 'paragraph',
      order: 3,
      text: 'terminal 数据流曾评估 TCP + UDS 双通道。TCP 暴露面大，且局域网场景没有真实需求——桌面端与 daemon 同机，远程场景由 SSH 转发承担。',
    },
    { id: 'b-4', type: 'heading', order: 4, depth: 2, text: '决定' },
    {
      id: 'b-5',
      type: 'paragraph',
      order: 5,
      text: 'gRPC 终端通道固定使用私有 UDS（$XDG_RUNTIME_DIR/qingluan/terminal.sock），daemon 不提供 TCP 终端端口。',
    },
    {
      id: 'b-6',
      type: 'list',
      order: 6,
      meta: { ordered: true },
      children: [
        { id: 'b-6-1', type: 'listItem', order: 1, text: 'UDS 路径仅属主可读写' },
        {
          id: 'b-6-2',
          type: 'listItem',
          order: 2,
          text: '互操作测试走 tests/terminal-grpc-interop',
        },
        {
          id: 'b-6-3',
          type: 'listItem',
          order: 3,
          text: 'TS 客户端封装在 packages/qingluan-client',
        },
      ],
    },
    {
      id: 'b-7',
      type: 'blockquote',
      order: 7,
      text: '代价：非本机客户端必须自行解决传输（SSH 隧道或 mosh），不内置。',
    },
    {
      id: 'b-8',
      type: 'code',
      order: 8,
      lang: 'toml',
      raw: '[terminal]\ntransport = "uds"\npath = "${XDG_RUNTIME_DIR}/qingluan/terminal.sock"',
    },
  ],
  'r-2405': [
    { id: 'b-1', type: 'heading', order: 1, depth: 1, text: 'BlockFrame 交互壳层' },
    {
      id: 'b-2',
      type: 'paragraph',
      order: 2,
      text: 'BlockFrame 是所有 block 的交互容器：选中态、悬停工具条与评论锚点都由它提供，内容渲染则下放给各 block 组件。',
    },
    {
      id: 'b-3',
      type: 'table',
      order: 3,
      meta: {
        table: {
          headers: ['组件', '职责'],
          rows: [
            ['BlockFrame', '交互壳层（选中/工具条/评论锚点）'],
            ['MarkdownDocument', '按 order 分发渲染'],
            ['MarkdownReviewLayout', '审查布局与侧栏'],
          ],
        },
      },
    },
    { id: 'b-4', type: 'hr', order: 4 },
    {
      id: 'b-5',
      type: 'paragraph',
      order: 5,
      text: '> 示例代码与 API 表格待补。',
    },
    { id: 'b-6', type: 'unknown', order: 6, raw: '新解析器输出的 block 类型先降级显示。' },
  ],
  'r-2406': [
    { id: 'b-1', type: 'heading', order: 1, depth: 1, text: '场景图预训练数据清洗 · 周报' },
    {
      id: 'b-2',
      type: 'paragraph',
      order: 2,
      text: '本周清理了 3 组离线场景图数据，剔除 12% 姿态漂移样本。剔除标准：连续 5 帧以上位姿跳变超过阈值。',
    },
    { id: 'b-3', type: 'heading', order: 3, depth: 2, text: '结论' },
    {
      id: 'b-4',
      type: 'paragraph',
      order: 4,
      text: '清洗后 val SPL 提升 2.4，但嵌入式端推理耗时增加 8ms，待评估是否接受。',
    },
    {
      id: 'b-5',
      type: 'code',
      order: 5,
      lang: 'python',
      raw: 'ds = SceneGraphDataset(root="data/clean-v3")\nloader = DataLoader(ds, batch_size=16, num_workers=4)',
    },
    {
      id: 'b-6',
      type: 'image',
      order: 6,
      text: '清洗前后 SPL 对比图',
      meta: { alt: '实验结果图占位' },
    },
  ],
  'r-2408': [
    { id: 'b-1', type: 'heading', order: 1, depth: 1, text: 'subagent 委派规范 v2' },
    {
      id: 'b-2',
      type: 'paragraph',
      order: 2,
      text: 'v1 的边界讨论过长；v2 收敛为「先描述、再授权、后回收」三段式。',
    },
    { id: 'b-3', type: 'blockquote', order: 3, text: '开放问题：委派失败的回滚语义尚未定稿。' },
  ],
  'r-2397': [
    { id: 'b-1', type: 'heading', order: 1, depth: 1, text: 'README 快速上手' },
    {
      id: 'b-2',
      type: 'paragraph',
      order: 2,
      text: '安装、启动 daemon、workspace 管理与桌面端使用说明（定稿版）。',
    },
    {
      id: 'b-3',
      type: 'code',
      order: 3,
      lang: 'bash',
      raw: 'qingluan daemon start\nqingluan workspace list',
    },
  ],
}
